[package]
name = "simple_restaurant_api"
version = "0.1.0"
edition = "2024"

[lib]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
chrono = { version = "0.4", features = ["serde", "alloc"] }
tracing = { version = "0.1" }
tokio = { version = "1.52", features = ["full"] }
futures = { version = "0.3" }